export enum WaitingStatus {
  WAITING = 'WAITING',
  ENTERED = 'ENTERED',
  EXITED = 'EXITED',
  CANCELED = 'CANCELED',
  CALLED = 'CALLED',
  DELAYED = 'DELAYED',
  NOSHOW = 'NOSHOW',
  EXITED_AND_READY = 'EXITED_AND_READY',
}
