export enum WaitingStatus {
  WAITING = 'WAITING',
  ENTERED = 'ENTERED',
  EXITED = 'EXITED',
  CANCELED = 'CANCELED',
  CALLED = 'CALLED',
  DELAYED = 'DELAYED',
  NOSHOW = 'NOSHOW',
  NOTFILLED = 'NOTFILLED',
}
